### ISSUE TITLE
The specified module could not be found.  (nyCollisionDeformer)

### ISSUE THREAD

**Issue by ban3bbal000** [nazmiprinter/ny_collisionDeformer#2]
Hi,

I'm trying to test your c++ deformer, but whenever I try to load the plugin I get this error. 
I have a custom Maya installation with custom environment_variables, but  I tried it with stock maya and got the same error just with a different place. 

Here is the Example:

Error: file: C:/Program Files/Autodesk/Maya2022/scripts/others/pluginWin.mel line 316: The specified module could not be found.
 (nyCollisionDeformer)
 
 The Python version loads properly, but I would like to test out the .mll as well.
 
 Do you have any solution for this?
 
 Thank you in advance

**Comment by nazmiprinter** [comment]
Hey,

Thank you for reaching out.
Please make sure that you place this file: github.com/nazmiprinter/ny_collisionDeformer/blob/master/cpp/maya2022/scripts/nyCollision_procs.mel

in a folder that's defined in your custom ENVVARs.

**Comment by ban3bbal000** [comment]
Hi. I placed the file in both the custom scripts folder and the original one. The error still occurs. Also, I tried on another computer where everything was set up originally and I got the same error.

**Comment by nazmiprinter** [comment]
Hi, I'll check this once I have time to install Maya 2022. Thanks for flagging.

**Comment by ban3bbal000** [comment]
Thank you. Can't wait to make this work.

**Comment by nazmiprinter** [comment]
Hey,

I installed Maya 2022 and ran the plugin just fine. I would advise you to double-check your custom environment variables.
The "nyCollisionDeformer.mll" should reside somewhere in "MAYA_PLUG_IN_PATH" and
the"nyCollision_procs.mel" should be in "MAYA_SCRIPT_PATH".

I hope this helps. Thanks!
